### ISSUE TITLE
Round robin assignment

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/hooky#10]
Instead of assigning all maintainers, hooky should assign one person.

The person assigned should be based on a magic string in the PR body, something like `primary-reviewer: @samuelcolvin`.

If there's no "primary-reviewer:" comment, someone should be selected on a round robin, or if round robin is hard, random basis. In this case, hooky should manually append `\n\nprimary-reviewer: @xxx` to the  PR body. This way, if no reviewer is "chosen" by the PR author, someone will be assigned and that person will be locked unless otherwise changed.

Good first issue, otherwise I'll do it when I get time.

**Comment by LX5321** [comment]
Hey @samuelcolvin I'd like to take up this issue, could you assign the same to me? Will have to run through the code and implement the feature.

Thanks.

**Comment by samuelcolvin** [comment]
Thanks so much, done.

**Comment by LX5321** [comment]
@samuelcolvin Pushed a fix for the same, will require some guidance on how to run the test suite locally though.

Thanks!

**Comment by LX5321** [comment]
We can close this since merged 👍🏼
